"""FastAPI application entry point for the Pi Assistant backend."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from . import calendar_tool
from .config import settings
from .openai_llm_client import chat_completion
from .schemas import ChatRequest, ScheduleRequest

app = FastAPI(title="Pi Assistant API")

# Allow the browser-based frontend to reach this API while developing locally.
origins = [origin.strip() for origin in settings.CORS_ORIGINS.split(",")]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SYSTEM_PROMPT = (
    "You are a concise personal assistant. "
    "If the user asks about schedule/calendar, say what you will do, then rely on tool results."
)


@app.post("/chat")
async def chat(req: ChatRequest):
    """Return a chat reply generated by the configured local LLM."""
    # Prepend the system prompt so the assistant consistently follows the desired tone.
    messages = [{"role": "system", "content": SYSTEM_PROMPT}] + [msg.dict() for msg in req.messages]
    out = await chat_completion(messages)
    return {"reply": out}


@app.get("/calendar/upcoming")
def upcoming(days: int = 7):
    """List the user's upcoming calendar events within the requested time window."""
    return {"text": calendar_tool.list_events(days)}


@app.post("/calendar/create")
def create(ev: ScheduleRequest):
    """Insert an event in the user's calendar and include the provider's shareable link."""
    link = calendar_tool.create_event(ev.title, ev.start_iso, ev.end_iso, ev.description)
    return {"status": "ok", "link": link}
